/**
 * Write design/ASSET_LIST.md from the asset contract in assets.ts.
 *
 *   npm run asset-list          (from the repo root)
 *
 * Generated rather than hand-written so the list cannot drift from the planets and events in
 * the engine, from the hotspot arrangements the backdrops have to be composed around, or from
 * what make-placeholders.ts actually puts on disk.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PLANETS } from '@sdr/engine';
import { arrangementNameFor, ARRANGEMENTS, HOTSPOT_VENUES } from '../src/lib/hotspots';
import { ARRANGEMENT_BRIEF, GROUPS, type AssetSpec } from './assets';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '..', '..', '..', 'design', 'ASSET_LIST.md');

const mb = (kb: number) => `${(kb / 1024).toFixed(1)} MB`;
const planetOfStem = (stem: string) => stem.split('/')[1] ?? '';

function assetHeading(a: AssetSpec): string {
  const extras: string[] = [
    `${a.w}×${a.h}`,
    a.alpha ? 'WebP with alpha' : 'WebP',
    `target ${a.targetKb} kB, cap ${a.capKb} kB`,
  ];
  if (a.group === 'backdrops') {
    const id = planetOfStem(a.stem);
    extras.push(`hotspot arrangement \`${arrangementNameFor(id)}\``);
  }
  extras.push(`seeds ${a.seeds}`);
  return (
    `#### ${a.label} — \`src/assets/${a.stem}.webp\`\n\n` +
    `${extras.join(' · ')}\n\n` +
    '```text\n' +
    `${a.prompt}\n` +
    '```\n'
  );
}

const out: string[] = [];
const push = (s = '') => out.push(s);

const total = GROUPS.flatMap((g) => g.assets);
const targetKb = total.reduce((n, a) => n + a.targetKb, 0);
const capKb = total.reduce((n, a) => n + a.capKb, 0);

push('# Space Dog Racing — asset list');
push();
push(
  '**The contract between the code and the art.** Every image the game will look for: where it ' +
    'goes, how big it is, what it may weigh, and a prompt you can paste straight into an image ' +
    'model with this planet’s vibe and its two accent hues already in it.',
);
push();
push(
  'Generated by `npm run asset-list` from `packages/web/scripts/assets.ts`, which reads the ' +
    'planets and the event deck out of the engine and the hotspot positions out of ' +
    '`packages/web/src/lib/hotspots.ts`. Edit that script, not this file — a hand edit here is ' +
    'gone the next time it runs.',
);
push();
push('---');
push();

// ---------------------------------------------------------------- how it works
push('## How dropping art in works');
push();
push(
  '1. Generate the image to the size in its entry and save it as **WebP** at exactly the path ' +
    'given, under `packages/web/src/assets/`.',
);
push(
  '2. That is all. Vite picks it up through a glob, fingerprints it into `dist/assets/`, and ' +
    'the game uses it on the next build. No code change, no import to add, no list to update.',
);
push(
  '3. **Placeholders are `.svg`, finished art is `.webp`.** `npm run placeholders` writes a ' +
    'labelled stand-in for every entry below. The resolver in `src/lib/assets.ts` prefers the ' +
    '`.webp`, so the moment yours lands it takes over — and every component that is still ' +
    'showing an `.svg` stamps PLACEHOLDER on itself, which disappears by itself when you ' +
    'replace it. Delete the `.svg` afterwards or leave it; nothing changes either way.',
);
push(
  '4. Nothing is ever missing enough to break a screen. A hub with no backdrop still paints its ' +
    'own chrome, a dog with no portrait shows a labelled slot, an event with no card shows a ' +
    'hatched panel. A blank screen is a bug, not a missing file.',
);
push();
push(
  'Everything is loaded lazily and per planet, so the whole set is never fetched at once. First ' +
    'paint is the app itself (~300 kB of JS and CSS, ~100 kB gzipped) plus the one backdrop for ' +
    'the planet you are standing on. A weekend costs one backdrop, one ground and one surface.',
);
push();

// ---------------------------------------------------------------- budget
push('## What the whole set weighs');
push();
push('| Group | Files | Target each | Target total | Cap total | Tier |');
push('|---|---:|---:|---:|---:|:--:|');
for (const g of GROUPS) {
  const t = g.assets.reduce((n, a) => n + a.targetKb, 0);
  const c = g.assets.reduce((n, a) => n + a.capKb, 0);
  const each = [...new Set(g.assets.map((a) => a.targetKb))].sort((x, y) => x - y);
  push(
    `| ${g.title} | ${g.assets.length} | ${each.join('/')} kB | ${mb(t)} | ${mb(c)} | ${g.tier} |`,
  );
}
push(`| **All of it** | **${total.length}** | | **${mb(targetKb)}** | **${mb(capKb)}** | |`);
push();
push(
  `**${total.length} files, about ${mb(targetKb)} if you hit the targets and ${mb(capKb)} if ` +
    'every one lands on its cap.** That is the whole library, not a download: no player ever ' +
    'fetches all of it, because backdrops, ground and surfaces are per planet and a season ' +
    'visits thirteen of eighteen.',
);
push();
push('Two levers if that total wants to come down:');
push();
push(
  '- **Tier 1 alone is 38 files and about 3.2 MB**, and it is most of the difference between ' +
    '"unfinished" and "finished": the 18 hub backdrops and the 20 dog layers. Generate that ' +
    'first, play it, and decide about the rest afterwards.',
);
push(
  '- **The race-view ground and surfaces (36 files, ~4.2 MB) can share.** Nothing in the code ' +
    'requires eighteen of each: copy one set across a family of planets that look alike — ice, ' +
    'desert, industrial, organic, urban, void — and six of each covers all eighteen for about ' +
    '1.4 MB. Same for a shared surface tile per family.',
);
push();
push(
  'Every entry says both a **target** (what a well-compressed export of that style should come ' +
    'to) and a **cap** (over this, re-export at a lower quality — the site is meant to feel ' +
    'instant on a phone). WebP quality 72–78 hits the targets for flat cel-shaded painting; ' +
    'transparent layers want 85 or the outlines go crunchy.',
);
push();

// ---------------------------------------------------------------- style
push('## The locked style');
push();
push(
  'Every prompt below already carries this, so you do not have to paste it separately. It is ' +
    'here so the whole set can be regenerated consistently if the look moves.',
);
push();
push('```text');
push(
  '1990s PC-game digital painting, chunky black outlines, flat cel shading, saturated grime —',
);
push(
  "Gazillionaire's pastel cartooning crossed with Death Rally's soot and neon, everything",
);
push('slightly held together with tape');
push('```');
push();
push(
  'Base palette (GDD §16): charcoal `#1B1A22`, rust `#6B3A22`, acid green `#9BE84B`, hazard ' +
    'yellow `#F4C542`, hot pink `#F04E98`, cyan `#3FD6E0`. Each planet overrides two accents, ' +
    'and those are already substituted into its prompts below — the same two hues the game ' +
    'reads out of `Planet.accents` to tint that planet’s chrome, so the art and the UI ' +
    'agree without anyone syncing them.',
);
push();
push(
  '**Seeds.** Every entry carries a hundred-wide seed band of its own. Re-roll inside the band ' +
    'and the family stays consistent; the bands never overlap, so two planets can never ' +
    'accidentally converge on the same image.',
);
push();

// ---------------------------------------------------------------- hotspots
push('## Where the hub hotspots sit');
push();
push(
  'Each hub backdrop has six clickable venue signs drawn over it. They are positioned from ' +
    '`packages/web/src/lib/hotspots.ts` as percentages of the frame, so the backdrop has to ' +
    'leave those six areas flat and uncluttered. Every backdrop prompt below already names its ' +
    'arrangement and lists the six coordinates.',
);
push();
push('| Arrangement | Composition | ' + HOTSPOT_VENUES.join(' | ') + ' |');
push('|---|---|' + HOTSPOT_VENUES.map(() => '---|').join(''));
for (const [name, arr] of Object.entries(ARRANGEMENTS)) {
  push(
    `| \`${name}\` | ${ARRANGEMENT_BRIEF[name] ?? ''} | ` +
      HOTSPOT_VENUES.map((v) => `${arr[v].x},${arr[v].y}`).join(' | ') +
      ' |',
  );
}
push();
push(
  'Also keep the **top-left** clear (the planet name plate sits there) and the ' +
    '**bottom-right corner** clear (the placeholder stamp, and later nothing at all).',
);
push();
push('Which planet uses which:');
push();
push('| Planet | Arrangement | Accents |');
push('|---|---|---|');
for (const p of PLANETS) {
  push(
    `| ${p.name} | \`${arrangementNameFor(p.id)}\` | \`${p.accents[0]}\` · \`${p.accents[1]}\` |`,
  );
}
push();

// ---------------------------------------------------------------- adding a planet
push('## Adding a nineteenth planet');
push();
push(
  'One data row in `packages/engine/src/content/planets.ts` — name, vibe, track, food band, ' +
    'special, and its two `accents` — plus three images:',
);
push();
push('```text');
push('packages/web/src/assets/planets/<id>/backdrop.webp   1920×1080');
push('packages/web/src/assets/planets/<id>/ground.webp     2048×2048');
push('packages/web/src/assets/planets/<id>/surface.webp    512×512, seamless');
push('```');
push();
push(
  'No code change. Hotspots fall back to the `arc` arrangement if the planet has no row in ' +
    '`lib/hotspots.ts`; add one to pick a different composition. The track shape comes from the ' +
    'planet’s own distance and bends, its chrome from its accents, and its rules from its ' +
    '`special` block.',
);
push();
push('---');
push();

// ---------------------------------------------------------------- the assets
push('# The files');
push();
push(
  'Tier 1 first: the 38 files that carry most of the difference. Tier 2 is the race view. ' +
    'Tier 3 is flavour, and every one of it degrades to something deliberate.',
);
push();

for (const tier of [1, 2, 3] as const) {
  push(`## Tier ${tier}`);
  push();
  for (const g of GROUPS.filter((x) => x.tier === tier)) {
    const t = g.assets.reduce((n, a) => n + a.targetKb, 0);
    push(`### ${g.title} — ${g.assets.length} files, ~${mb(t)}`);
    push();
    push(g.blurb);
    push();
    push('**Negative prompt for every file in this group:**');
    push();
    push('```text');
    push(g.assets[0]!.negative);
    push('```');
    push();
    for (const a of g.assets) push(assetHeading(a));
  }
}

push('---');
push();
push(
  '*Written by `npm run asset-list`. Placeholders for every entry above come from ' +
    '`npm run placeholders`.*',
);

writeFileSync(OUT, `${out.join('\n')}\n`, 'utf8');
console.log(`design/ASSET_LIST.md written — ${total.length} assets, ${out.length} lines.`);
